In [2]:
import pandas as pd
import db_mgmt as mgmt
import os

In [3]:
os.getcwd()

'/Users/thiagorodrigues/Documents/CANOE/CANOE_ref'

In [314]:
data_schema = 'dbs/canoe_dataset_schema 4.sql'
db_file = 'dbs/canoe_transport.sqlite'
os.remove(db_file) if os.path.exists(db_file) else None
mgmt.convert_sql_to_sqlite(data_schema, db_file)
data = mgmt.sqlite_to_dfs(db_file)
data.keys()

dict_keys(['MetaData', 'MetaDataReal', 'SeasonLabel', 'SectorLabel', 'CapacityCredit', 'CapacityFactorProcess', 'CapacityFactorTech', 'CapacityToActivity', 'Commodity', 'CommodityType', 'ConstructionInput', 'CostEmission', 'CostFixed', 'CostInvest', 'CostVariable', 'Demand', 'DemandSpecificDistribution', 'EndOfLifeOutput', 'Efficiency', 'EfficiencyVariable', 'EmissionActivity', 'EmissionEmbodied', 'EmissionEndOfLife', 'ExistingCapacity', 'TechGroup', 'LoanLifetimeProcess', 'LoanRate', 'LifetimeProcess', 'LifetimeTech', 'Operator', 'LimitGrowthCapacity', 'LimitDegrowthCapacity', 'LimitGrowthNewCapacity', 'LimitDegrowthNewCapacity', 'LimitGrowthNewCapacityDelta', 'LimitDegrowthNewCapacityDelta', 'LimitStorageLevelFraction', 'LimitActivity', 'LimitActivityShare', 'LimitAnnualCapacityFactor', 'LimitCapacity', 'LimitCapacityShare', 'LimitNewCapacity', 'LimitNewCapacityShare', 'LimitResource', 'LimitSeasonalCapacityFactor', 'LimitTechInputSplit', 'LimitTechInputSplitAnnual', 'LimitTechOutputSplit', 'LimitTechOutputSplitAnnual', 'LimitEmission', 'LinkedTech', 'PlanningReserveMargin', 'RampDownHourly', 'RampUpHourly', 'Region', 'ReserveCapacityDerate', 'TimeSegmentFraction', 'StorageDuration', 'LifetimeSurvivalCurve', 'TechnologyType', 'TimeOfDay', 'TimePeriod', 'TimeSeason', 'TimeSeasonSequential', 'TimePeriodType', 'RPSRequirement', 'TechGroupMember', 'Technology', 'DataSource', 'DataQualityCredibility', 'DataQualityGeography', 'DataQualityStructure', 'DataQualityTechnology', 'DataQualityTime', 'DataSet'])

In [315]:
dir = 'transport/inputs/'
transp = {}
for file in os.listdir(dir):
    #print(file)
    if file.endswith('.csv'):
        transp[file.split('_')[0]] = pd.read_csv(dir + file)

In [316]:
tech_to_remove = pd.read_csv('transport/Fuel_techs.csv')['tech'].to_list()
new_transp = {}
fuel = {}
transport = {}

for table, df in transp.items():
    if 'tech' in df.columns:
        fuel[table] = df[df['tech'].isin(tech_to_remove)].copy().reset_index(drop=True)
        new_transp[table] = df[~df['tech'].isin(tech_to_remove)].copy().reset_index(drop=True)
        print(table)
    else:
        new_transp[table] = df.copy()

ExistingCapacity
CapacityFactorTech
LimitTechInputSplitAnnual
LimitAnnualCapacityFactor
CostFixed
TechGroupMember
Technology
EmissionActivity
LifetimeTech
CostInvest
CapacityToActivity
LifetimeSurvivalCurve
CostVariable
Efficiency

In [317]:
comm = pd.read_csv('transport/Fuel_comm.csv')['commodity'].to_list()
comm

['T_h2_10', 'T_h2_100', 'T_elc_dc', 'T_ng', 'T_h2']

In [318]:
new_transp['Commodity'] = pd.read_csv('transport/Commodity.csv')
new_transp['CostFixed'] = pd.read_csv('dbs/CostFixed.csv')
new_transp['CostInvest'] = pd.read_csv('dbs/CostInvest.csv')
fuel['Commodity'] = pd.read_csv('transport/Commodity_fuel.csv')

In [319]:
for table, df in new_transp.items():
    for c in comm:
        if c in df.values:
            new_transp[table] = df[~df.isin([c]).any(axis=1)].copy().reset_index(drop=True)
            print(table)

print('\nfuel')
for table, df in fuel.items():
    for c in comm:
        if c in df.values:
            fuel[table] = df[df.isin([c]).any(axis=1)].copy().reset_index(drop=True)
            print(table)

fuel
LimitTechInputSplitAnnual
LimitTechInputSplitAnnual
LimitAnnualCapacityFactor
EmissionActivity
EmissionActivity
Efficiency
Efficiency
Efficiency
Efficiency
Efficiency
Commodity
Commodity
Commodity
Commodity

In [320]:
for table, df in new_transp.items():
    print(table)
    if ('data_id' in data[table].columns) and (table != 'DataSet'):
        if 'region' not in df.columns:
            df['data_id'] = 'TRPHR002'
        else:
            df['data_id'] = 'TRPHR' + df['region'].astype(str) + '002'

DataSource
ExistingCapacity
DataSet
CapacityFactorTech
LimitTechInputSplitAnnual
LimitAnnualCapacityFactor
CostFixed
TechGroupMember
Technology
EmissionActivity
LifetimeTech
CostInvest
Demand
CapacityToActivity
LifetimeSurvivalCurve
Commodity
CostVariable
TechGroup
Efficiency

In [321]:
new_transp['Technology']['tech'].to_list()

['T_BLND_DSL_ELC_HDV',
 'T_BLND_DSL_ELC_MDV',
 'T_BLND_ETH_GSL',
 'T_BLND_GSL_ELC_PHEV35',
 'T_BLND_GSL_ELC_PHEV50',
 'T_BLND_JTF',
 'T_BLND_RDSL_DSL',
 'T_BLND_SPK',
 'T_H2_HDV_REFUEL',
 'T_H2_LDV_REFUEL',
 'T_H2_MDV_REFUEL',
 'T_HDV_AJF_JFL',
 'T_HDV_AJF_SPK',
 'T_HDV_AJP_JFL',
 'T_HDV_AJP_SPK',
 'T_HDV_BIC_BEV',
 'T_HDV_BIC_DSL',
 'T_HDV_BIC_DSL_HEV',
 'T_HDV_BIC_FCEV',
 'T_HDV_BIC_GSL',
 'T_HDV_BS_BEV',
 'T_HDV_BS_CNG',
 'T_HDV_BS_DSL',
 'T_HDV_BS_DSL_HEV',
 'T_HDV_BS_DSL_PHEV',
 'T_HDV_BS_FCEV',
 'T_HDV_BS_FCHEV',
 'T_HDV_BS_GSL',
 'T_HDV_BT_BEV',
 'T_HDV_BT_CNG',
 'T_HDV_BT_DSL',
 'T_HDV_BT_DSL_HEV',
 'T_HDV_BT_DSL_PHEV',
 'T_HDV_BT_FCEV',
 'T_HDV_BT_FCHEV',
 'T_HDV_BT_GSL',
 'T_HDV_CHRG',
 'T_HDV_RF_DSL',
 'T_HDV_RF_H2',
 'T_HDV_RF_LNG',
 'T_HDV_RICP_DSL',
 'T_HDV_RICP_H2',
 'T_HDV_T_BEV',
 'T_HDV_T_DSL',
 'T_HDV_T_DSL_HEV',
 'T_HDV_T_DSL_PHEV',
 'T_HDV_T_FCEV',
 'T_HDV_T_FCHEV',
 'T_HDV_WTF_HFO',
 'T_HDV_WTF_LNG',
 'T_HDV_WTF_MDO',
 'T_LDV_BEV_CHRG',
 'T_LDV_C_BEV150',
 'T_LDV_C_BEV200',
 'T_LDV_C_BEV300',
 'T_LDV_C_BEV400',
 'T_LDV_C_CNG',
 'T_LDV_C_DSL',
 'T_LDV_C_FCEV400',
 'T_LDV_C_GSL',
 'T_LDV_C_GSL_HEV',
 'T_LDV_C_GSL_PHEV35',
 'T_LDV_C_GSL_PHEV50',
 'T_LDV_LTF_BEV150',
 'T_LDV_LTF_BEV200',
 'T_LDV_LTF_BEV300',
 'T_LDV_LTF_BEV400',
 'T_LDV_LTF_CNG',
 'T_LDV_LTF_DSL',
 'T_LDV_LTF_FCEV400',
 'T_LDV_LTF_GSL',
 'T_LDV_LTF_GSL_HEV',
 'T_LDV_LTF_GSL_PHEV35',
 'T_LDV_LTF_GSL_PHEV50',
 'T_LDV_LTP_BEV150',
 'T_LDV_LTP_BEV200',
 'T_LDV_LTP_BEV300',
 'T_LDV_LTP_BEV400',
 'T_LDV_LTP_CNG',
 'T_LDV_LTP_DSL',
 'T_LDV_LTP_FCEV400',
 'T_LDV_LTP_GSL',
 'T_LDV_LTP_GSL_HEV',
 'T_LDV_LTP_GSL_PHEV35',
 'T_LDV_LTP_GSL_PHEV50',
 'T_LDV_M_BEV',
 'T_LDV_M_GSL',
 'T_LDV_PHEV_CHRG',
 'T_MDV_CHRG',
 'T_MDV_T_BEV',
 'T_MDV_T_DSL',
 'T_MDV_T_DSL_HEV',
 'T_MDV_T_DSL_PHEV',
 'T_MDV_T_FCEV',
 'T_MDV_T_FCHEV',
 'T_MDV_T_GSL',
 'T_OFF']

In [322]:
for table, df in new_transp.items():
    if "tech" in df.columns:
        print(table)
        print('')
        sub_df = df.loc[~df['tech'].isin(techs_trans)]
        if len(sub_df) > 0:
            print(sub_df['tech'].unique())

ExistingCapacity

CapacityFactorTech

LimitTechInputSplitAnnual

LimitAnnualCapacityFactor

CostFixed

TechGroupMember

Technology

EmissionActivity

LifetimeTech

['T_HDV_AJF_JFL_EX' 'T_HDV_AJF_JFL_N' 'T_HDV_AJF_SPK_N' 'T_HDV_AJP_JFL_EX'
 'T_HDV_AJP_JFL_N' 'T_HDV_AJP_SPK_N' 'T_HDV_BIC_BEV_N' 'T_HDV_BIC_DSL_EX'
 'T_HDV_BIC_DSL_HEV_N' 'T_HDV_BIC_DSL_N' 'T_HDV_BIC_FCEV_N'
 'T_HDV_BIC_GSL_EX' 'T_HDV_BIC_GSL_N' 'T_HDV_BS_BEV_N' 'T_HDV_BS_CNG_EX'
 'T_HDV_BS_CNG_N' 'T_HDV_BS_DSL_EX' 'T_HDV_BS_DSL_HEV_N' 'T_HDV_BS_DSL_N'
 'T_HDV_BS_DSL_PHEV_N' 'T_HDV_BS_FCEV_N' 'T_HDV_BS_FCHEV_N'
 'T_HDV_BS_GSL_EX' 'T_HDV_BS_GSL_N' 'T_HDV_BT_BEV_EX' 'T_HDV_BT_BEV_N'
 'T_HDV_BT_CNG_EX' 'T_HDV_BT_CNG_N' 'T_HDV_BT_DSL_EX' 'T_HDV_BT_DSL_HEV_N'
 'T_HDV_BT_DSL_N' 'T_HDV_BT_DSL_PHEV_N' 'T_HDV_BT_FCEV_N'
 'T_HDV_BT_FCHEV_N' 'T_HDV_BT_GSL_EX' 'T_HDV_BT_GSL_N' 'T_HDV_RF_DSL_EX'
 'T_HDV_RF_DSL_N' 'T_HDV_RF_H2_N' 'T_HDV_RF_LNG_N' 'T_HDV_RICP_DSL_EX'
 'T_HDV_RICP_DSL_N' 'T_HDV_RICP_H2_N' 'T_HDV_WTF_HFO_EX' 'T_HDV_WTF_HFO_N'
 'T_HDV_WTF_LNG_N' 'T_HDV_WTF_MDO_EX' 'T_HDV_WTF_MDO_N' 'T_LDV_M_BEV_N'
 'T_LDV_M_GSL_EX' 'T_LDV_M_GSL_N']
CostInvest

CapacityToActivity

LifetimeSurvivalCurve

CostVariable

Efficiency

In [323]:
df = new_transp['LifetimeTech'].copy()


new = df.loc[df['tech'].str.endswith('_N'), 'tech'].to_list()
replacer = {tech: tech[:-2] for tech in new}

ex = df.loc[df['tech'].str.endswith('_EX'), 'tech'].to_list()
replacer.update({tech: tech[:-3] for tech in ex})
replacer

df = df.replace(replacer)

df.drop_duplicates(subset=['region', 'tech'])

new_transp['LifetimeTech'] = df.copy()

In [324]:
mgmt.update_sqlite(db_file, new_transp)

Inserting into DataSource with columns: source_id,source,notes,data_id
Inserting into ExistingCapacity with columns: region,tech,vintage,capacity,units,notes,data_source,dq_cred,dq_geog,dq_struc,dq_tech,dq_time,data_id
Inserting into DataSet with columns: data_id,label,version,description,status,author,date,parent_id,changelog,notes
Inserting into CapacityFactorTech with columns: region,period,season,tod,tech,factor,notes,data_source,dq_cred,dq_geog,dq_struc,dq_tech,dq_time,data_id
Inserting into LimitTechInputSplitAnnual with columns: region,period,input_comm,tech,operator,proportion,notes,data_source,dq_cred,dq_geog,dq_struc,dq_tech,dq_time,data_id
Inserting into LimitAnnualCapacityFactor with columns: region,tech,vintage,output_comm,operator,factor,notes,data_source,dq_cred,dq_geog,dq_struc,dq_tech,dq_time,data_id
Inserting into CostFixed with columns: region,period,tech,vintage,cost,data_id
Inserting into TechGroupMember with columns: group_name,tech,data_id
Inserting into Technology with columns: tech,flag,sector,category,sub_category,unlim_cap,annual,reserve,curtail,retire,flex,exchange,seas_stor,description,data_id
Inserting into EmissionActivity with columns: region,emis_comm,input_comm,tech,vintage,output_comm,activity,units,notes,data_source,dq_cred,dq_geog,dq_struc,dq_tech,dq_time,data_id
Inserting into LifetimeTech with columns: region,tech,lifetime,notes,data_source,dq_cred,dq_geog,dq_struc,dq_tech,dq_time,data_id
Inserting into CostInvest with columns: region,tech,vintage,cost,notes,data_id
Inserting into Demand with columns: region,period,commodity,demand,units,notes,data_source,dq_cred,dq_geog,dq_struc,dq_tech,dq_time,data_id
Inserting into CapacityToActivity with columns: region,tech,c2a,notes,data_id,data_source,dq_cred,dq_geog,dq_struc,dq_tech,dq_time
Inserting into LifetimeSurvivalCurve with columns: region,tech,vintage,period,fraction,notes,data_id
Inserting into Commodity with columns: name,flag,description,data_id
Inserting into CostVariable with columns: region,period,tech,vintage,cost,units,notes,data_source,dq_cred,dq_geog,dq_struc,dq_tech,dq_time,data_id
Inserting into TechGroup with columns: group_name,data_id
Inserting into Efficiency with columns: region,input_comm,tech,vintage,output_comm,efficiency,notes,data_source,dq_cred,dq_geog,dq_struc,dq_tech,dq_time,data_id

In [ ]:
ind_h2 = mgmt.sqlite_to_dfs('dbs/residential/industry.sqlite')
# db_file_h2 = 'dbs/industry_h2.sqlite'
# ind_h2 = mgmt.convert_sql_to_sqlite(data_schema, db_file_h2)

{'MetaData':            element  value                         notes
 0         DB_MAJOR      3       DB major version number
 1         DB_MINOR      1       DB minor version number
 2  days_per_period    365  count of days in each period,
 'MetaDataReal':                 element  value                          notes
 0  global_discount_rate   0.03  Canadian social discount rate
 1     default_loan_rate   0.03                   Matching GDR,
 'SeasonLabel': Empty DataFrame
 Columns: [season, notes]
 Index: [],
 'SectorLabel': Empty DataFrame
 Columns: [sector, notes]
 Index: [],
 'CapacityCredit': Empty DataFrame
 Columns: [region, period, tech, vintage, credit, notes, data_source, dq_cred, dq_geog, dq_struc, dq_tech, dq_time, data_id]
 Index: [],
 'CapacityFactorProcess': Empty DataFrame
 Columns: [region, period, season, tod, tech, vintage, factor, notes, data_source, dq_cred, dq_geog, dq_struc, dq_tech, dq_time, data_id]
 Index: [],
 'CapacityFactorTech': Empty DataFrame
 Columns: [region, period, season, tod, tech, factor, notes, data_source, dq_cred, dq_geog, dq_struc, dq_tech, dq_time, data_id]
 Index: [],
 'CapacityToActivity': Empty DataFrame
 Columns: [region, tech, c2a, notes, data_source, dq_cred, dq_geog, dq_struc, dq_tech, dq_time, data_id]
 Index: [],
 'Commodity':             name flag                                        description  \
 0          I_elc    a    Represents Electricity in the industrial sector
 1           I_ng    a    Represents Natural Gas in the industrial sector
 2          I_dsl    a         Represents Diesel in the industrial sector
 3          I_hfo    a  Represents Heavy Fuel Oil in the industrial se...
 4        I_pcoke    a  Represents Petroleum Coke in the industrial se...
 5          I_ngl    a  Represents Natural Gas Liquids in the industri...
 6         I_coal    a           Represents Coal in the industrial sector
 7         I_coke    a           Represents Coke in the industrial sector
 8         I_wood    a           Represents Wood in the industrial sector
 9          I_oth    a          Represents Other in the industrial sector
 10       I_d_con    d                 Demand for the Construction sector
 11      I_d_pulp    d               Demand for the Pulp and paper sector
 12     I_d_smelt    d                     Demand for the Smelting sector
 13  I_d_refining    d           Demand for the Petroleum refining sector
 14    I_d_cement    d                       Demand for the Cement sector
 15      I_d_chem    d                     Demand for the Chemical sector
 16     I_d_steel    d               Demand for the Iron and Steel sector
 17   I_d_oth_man    d          Demand for the Other manufacturing sector
 18       I_d_for    d                     Demand for the Forestry sector
 19    I_d_mining    d  Demand for the Mining and Oil & Gas extraction...

      data_id
 0   INDHR002
 1   INDHR002
 2   INDHR002
 3   INDHR002
 4   INDHR002
 5   INDHR002
 6   INDHR002
 7   INDHR002
 8   INDHR002
 9   INDHR002
 10  INDHR002
 11  INDHR002
 12  INDHR002
 13  INDHR002
 14  INDHR002
 15  INDHR002
 16  INDHR002
 17  INDHR002
 18  INDHR002
 19  INDHR002  ,
 'CommodityType':   label               description
 0     s          source commodity
 1     a          annual commodity
 2     p        physical commodity
 3     d          demand commodity
 4     e       emissions commodity
 5     w           waste commodity
 6    wa    waste annual commodity
 7    wp  waste physical commodity,
 'ConstructionInput': Empty DataFrame
 Columns: [region, input_comm, tech, vintage, value, units, notes, data_source, dq_cred, dq_geog, dq_struc, dq_tech, dq_time, data_id]
 Index: [],
 'CostEmission': Empty DataFrame
 Columns: [region, period, emis_comm, cost, units, notes, data_source, dq_cred, dq_geog, dq_struc, dq_tech, dq_time, data_id]
 Index: [],
 'CostFixed': Empty DataFrame
 Columns: [region, period, tech, vintage, cost, units, notes, data_source, dq_cred, dq_geog, dq_struc, dq_tech, dq_time, data_id]
 Index: [],
 'CostInvest': Empty DataFrame
 Columns: [region, tech, vintage, cost, units, notes, data_source, dq_cred, dq_geog, dq_struc, dq_tech, dq_time, data_id]
 Index: [],
 'CostVariable': Empty DataFrame
 Columns: [region, period, tech, vintage, cost, units, notes, data_source, dq_cred, dq_geog, dq_struc, dq_tech, dq_time, data_id]
 Index: [],
 'Demand':     region  period     commodity     demand units  \
 0       AB    2025       I_d_con  19.531597    PJ
 1       AB    2025      I_d_pulp  89.914691    PJ
 2       AB    2025     I_d_smelt   0.577858    PJ
 3       AB    2025  I_d_refining  91.185978    PJ
 4       AB    2025    I_d_cement  13.637447    PJ
 ..     ...     ...           ...        ...   ...
 425  NLLAB    2045     I_d_smelt   2.419049    PJ
 426  NLLAB    2045      I_d_chem   0.224791    PJ
 427  NLLAB    2045   I_d_oth_man   2.161039    PJ
 428  NLLAB    2045       I_d_for   0.747919    PJ
 429  NLLAB    2045    I_d_mining  25.360320    PJ

                                                  notes data_source  dq_cred  \
 0    GDP-scaled from NRCan 2022 baseline to data ye...        [I2]        1
 1    GDP-scaled from NRCan 2022 baseline to data ye...        [I2]        1
 2    GDP-scaled from NRCan 2022 baseline to data ye...        [I2]        1
 3    GDP-scaled from NRCan 2022 baseline to data ye...        [I2]        1
 4    GDP-scaled from NRCan 2022 baseline to data ye...        [I2]        1
 ..                                                 ...         ...      ...
 425  GDP-scaled from NRCan 2022 ATL baseline to dat...        [I4]        1
 426  GDP-scaled from NRCan 2022 ATL baseline to dat...        [I4]        1
 427  GDP-scaled from NRCan 2022 ATL baseline to dat...        [I4]        1
 428  GDP-scaled from NRCan 2022 ATL baseline to dat...        [I4]        1
 429  GDP-scaled from NRCan 2022 ATL baseline to dat...        [I4]        1

      dq_geog  dq_struc  dq_tech  dq_time        data_id
 0          1         2        3        2     INDHRAB002
 1          1         2        3        2     INDHRAB002
 2          1         2        3        2     INDHRAB002
 3          1         2        3        2     INDHRAB002
 4          1         2        3        2     INDHRAB002
 ..       ...       ...      ...      ...            ...
 425        1         2        3        2  INDHRNLLAB002
 426        1         2        3        2  INDHRNLLAB002
 427        1         2        3        2  INDHRNLLAB002
 428        1         2        3        2  INDHRNLLAB002
 429        1         2        3        2  INDHRNLLAB002

 [430 rows x 13 columns],
 'DemandSpecificDistribution': Empty DataFrame
 Columns: [region, period, season, tod, demand_name, dsd, notes, data_source, dq_cred, dq_geog, dq_struc, dq_tech, dq_time, data_id]
 Index: [],
 'EndOfLifeOutput': Empty DataFrame
 Columns: [region, tech, vintage, output_comm, value, units, notes, data_source, dq_cred, dq_geog, dq_struc, dq_tech, dq_time, data_id]
 Index: [],
 'Efficiency':      region input_comm      tech  vintage output_comm  efficiency  \
 0        AB      I_elc     I_CON     2025     I_d_con         1.0
 1        AB       I_ng     I_CON     2025     I_d_con         1.0
 2        AB      I_dsl     I_CON     2025     I_d_con         1.0
 3        AB      I_ngl     I_CON     2025     I_d_con         1.0
 4        AB      I_elc    I_PULP     2025    I_d_pulp         1.0
 ...     ...        ...       ...      ...         ...         ...
 1925  NLLAB      I_elc  I_MINING     2045  I_d_mining         1.0
 1926  NLLAB      I_dsl  I_MINING     2045  I_d_mining         1.0
 1927  NLLAB      I_hfo  I_MINING     2045  I_d_mining         1.0
 1928  NLLAB      I_ngl  I_MINING     2045  I_d_mining         1.0
 1929  NLLAB     I_coke  I_MINING     2045  I_d_mining         1.0

                                                   notes data_source dq_cred  \
 0     All technologies are assumed to have arbitrary...        [I1]    None
 1     All technologies are assumed to have arbitrary...        [I1]    None
 2     All technologies are assumed to have arbitrary...        [I1]    None
 3     All technologies are assumed to have arbitrary...        [I1]    None
 4     All technologies are assumed to have arbitrary...        [I1]    None
 ...                                                 ...         ...     ...
 1925  All technologies are assumed to have arbitrary...        [I1]    None
 1926  All technologies are assumed to have arbitrary...        [I1]    None
 1927  All technologies are assumed to have arbitrary...        [I1]    None
 1928  All technologies are assumed to have arbitrary...        [I1]    None
 1929  All technologies are assumed to have arbitrary...        [I1]    None

      dq_geog dq_struc dq_tech dq_time        data_id
 0       None     None    None    None     INDHRAB002
 1       None     None    None    None     INDHRAB002
 2       None     None    None    None     INDHRAB002
 3       None     None    None    None     INDHRAB002
 4       None     None    None    None     INDHRAB002
 ...      ...      ...     ...     ...            ...
 1925    None     None    None    None  INDHRNLLAB002
 1926    None     None    None    None  INDHRNLLAB002
 1927    None     None    None    None  INDHRNLLAB002
 1928    None     None    None    None  INDHRNLLAB002
 1929    None     None    None    None  INDHRNLLAB002

 [1930 rows x 14 columns],
 'EfficiencyVariable': Empty DataFrame
 Columns: [region, period, season, tod, input_comm, tech, vintage, output_comm, efficiency, notes, data_source, dq_cred, dq_geog, dq_struc, dq_tech, dq_time, data_id]
 Index: [],
 'EmissionActivity': Empty DataFrame
 Columns: [region, emis_comm, input_comm, tech, vintage, output_comm, activity, units, notes, data_source, dq_cred, dq_geog, dq_struc, dq_tech, dq_time, data_id]
 Index: [],
 'EmissionEmbodied': Empty DataFrame
 Columns: [region, emis_comm, tech, vintage, value, units, notes, data_source, dq_cred, dq_geog, dq_struc, dq_tech, dq_time, data_id]
 Index: [],
 'EmissionEndOfLife': Empty DataFrame
 Columns: [region, emis_comm, tech, vintage, value, units, notes, data_source, dq_cred, dq_geog, dq_struc, dq_tech, dq_time, data_id]
 Index: [],
 'ExistingCapacity': Empty DataFrame
 Columns: [region, tech, vintage, capacity, units, notes, data_source, dq_cred, dq_geog, dq_struc, dq_tech, dq_time, data_id]
 Index: [],
 'TechGroup': Empty DataFrame
 Columns: [group_name, notes, data_id]
 Index: [],
 'LoanLifetimeProcess': Empty DataFrame
 Columns: [region, tech, vintage, lifetime, notes, data_source, dq_cred, dq_geog, dq_struc, dq_tech, dq_time, data_id]
 Index: [],
 'LoanRate': Empty DataFrame
 Columns: [region, tech, vintage, rate, notes, data_source, dq_cred, dq_geog, dq_struc, dq_tech, dq_time, data_id]
 Index: [],
 'LifetimeProcess': Empty DataFrame
 Columns: [region, tech, vintage, lifetime, notes, data_source, dq_cred, dq_geog, dq_struc, dq_tech, dq_time, data_id]
 Index: [],
 'LifetimeTech': Empty DataFrame
 Columns: [region, tech, lifetime, notes, data_source, dq_cred, dq_geog, dq_struc, dq_tech, dq_time, data_id]
 Index: [],
 'Operator':   operator                     notes
 0        e                  equal to
 1       le     less than or equal to
 2       ge  greater than or equal to,
 'LimitGrowthCapacity': Empty DataFrame
 Columns: [region, tech_or_group, operator, rate, seed, seed_units, notes, data_source, dq_cred, dq_geog, dq_struc, dq_tech, dq_time, data_id]
 Index: [],
 'LimitDegrowthCapacity': Empty DataFrame
 Columns: [region, tech_or_group, operator, rate, seed, seed_units, notes, data_source, dq_cred, dq_geog, dq_struc, dq_tech, dq_time, data_id]
 Index: [],
 'LimitGrowthNewCapacity': Empty DataFrame
 Columns: [region, tech_or_group, operator, rate, seed, seed_units, notes, data_source, dq_cred, dq_geog, dq_struc, dq_tech, dq_time, data_id]
 Index: [],
 'LimitDegrowthNewCapacity': Empty DataFrame
 Columns: [region, tech_or_group, operator, rate, seed, seed_units, notes, data_source, dq_cred, dq_geog, dq_struc, dq_tech, dq_time, data_id]
 Index: [],
 'LimitGrowthNewCapacityDelta': Empty DataFrame
 Columns: [region, tech_or_group, operator, rate, seed, seed_units, notes, data_source, dq_cred, dq_geog, dq_struc, dq_tech, dq_time, data_id]
 Index: [],
 'LimitDegrowthNewCapacityDelta': Empty DataFrame
 Columns: [region, tech_or_group, operator, rate, seed, seed_units, notes, data_source, dq_cred, dq_geog, dq_struc, dq_tech, dq_time, data_id]
 Index: [],
 'LimitStorageLevelFraction': Empty DataFrame
 Columns: [region, period, season, tod, tech, vintage, operator, fraction, notes, data_source, dq_cred, dq_geog, dq_struc, dq_tech, dq_time, data_id]
 Index: [],
 'LimitActivity': Empty DataFrame
 Columns: [region, period, tech_or_group, operator, activity, units, notes, data_source, dq_cred, dq_geog, dq_struc, dq_tech, dq_time, data_id]
 Index: [],
 'LimitActivityShare': Empty DataFrame
 Columns: [region, period, sub_group, super_group, operator, share, notes, data_source, dq_cred, dq_geog, dq_struc, dq_tech, dq_time, data_id]
 Index: [],
 'LimitAnnualCapacityFactor': Empty DataFrame
 Columns: [region, tech, vintage, output_comm, operator, factor, notes, data_source, dq_cred, dq_geog, dq_struc, dq_tech, dq_time, data_id]
 Index: [],
 'LimitCapacity': Empty DataFrame
 Columns: [region, period, tech_or_group, operator, capacity, units, notes, data_source, dq_cred, dq_geog, dq_struc, dq_tech, dq_time, data_id]
 Index: [],
 'LimitCapacityShare': Empty DataFrame
 Columns: [region, period, sub_group, super_group, operator, share, notes, data_source, dq_cred, dq_geog, dq_struc, dq_tech, dq_time, data_id]
 Index: [],
 'LimitNewCapacity': Empty DataFrame
 Columns: [region, period, tech_or_group, operator, new_cap, units, notes, data_source, dq_cred, dq_geog, dq_struc, dq_tech, dq_time, data_id]
 Index: [],
 'LimitNewCapacityShare': Empty DataFrame
 Columns: [region, period, sub_group, super_group, operator, share, notes, data_source, dq_cred, dq_geog, dq_struc, dq_tech, dq_time, data_id]
 Index: [],
 'LimitResource': Empty DataFrame
 Columns: [region, tech_or_group, operator, cum_act, units, notes, data_source, dq_cred, dq_geog, dq_struc, dq_tech, dq_time, data_id]
 Index: [],
 'LimitSeasonalCapacityFactor': Empty DataFrame
 Columns: [region, period, season, tech, operator, factor, notes, data_source, dq_cred, dq_geog, dq_struc, dq_tech, dq_time, data_id]
 Index: [],
 'LimitTechInputSplit': Empty DataFrame
 Columns: [region, period, input_comm, tech, operator, proportion, notes, data_source, dq_cred, dq_geog, dq_struc, dq_tech, dq_time, data_id]
 Index: [],
 'LimitTechInputSplitAnnual':      region  period input_comm      tech operator  proportion  \
 0        AB    2025      I_elc     I_CON       ge       0.001
 1        AB    2025       I_ng     I_CON       ge       0.335
 2        AB    2025      I_dsl     I_CON       ge       0.468
 3        AB    2025      I_ngl     I_CON       ge       0.196
 4        AB    2025      I_elc    I_PULP       ge       0.143
 ...     ...     ...        ...       ...      ...         ...
 1925  NLLAB    2045      I_elc  I_MINING       ge       0.396
 1926  NLLAB    2045      I_dsl  I_MINING       ge       0.192
 1927  NLLAB    2045      I_hfo  I_MINING       ge       0.232
 1928  NLLAB    2045      I_ngl  I_MINING       ge       0.010
 1929  NLLAB    2045     I_coke  I_MINING       ge       0.170

                                                   notes data_source  dq_cred  \
 0     Calculated from NRCan 2022 comprehensive datab...        [I1]        2
 1     Calculated from NRCan 2022 comprehensive datab...        [I1]        2
 2     Calculated from NRCan 2022 comprehensive datab...        [I1]        2
 3     Calculated from NRCan 2022 comprehensive datab...        [I1]        2
 4     Calculated from NRCan 2022 comprehensive datab...        [I1]        2
 ...                                                 ...         ...      ...
 1925  Calculated from NRCan 2022 comprehensive datab...        [I1]        2
 1926  Calculated from NRCan 2022 comprehensive datab...        [I1]        2
 1927  Calculated from NRCan 2022 comprehensive datab...        [I1]        2
 1928  Calculated from NRCan 2022 comprehensive datab...        [I1]        2
 1929  Calculated from NRCan 2022 comprehensive datab...        [I1]        2

       dq_geog  dq_struc  dq_tech  dq_time        data_id
 0           1         2        3        3     INDHRAB002
 1           1         2        3        3     INDHRAB002
 2           1         2        3        3     INDHRAB002
 3           1         2        3        3     INDHRAB002
 4           1         2        3        3     INDHRAB002
 ...       ...       ...      ...      ...            ...
 1925        1         2        3        3  INDHRNLLAB002
 1926        1         2        3        3  INDHRNLLAB002
 1927        1         2        3        3  INDHRNLLAB002
 1928        1         2        3        3  INDHRNLLAB002
 1929        1         2        3        3  INDHRNLLAB002

 [1930 rows x 14 columns],
 'LimitTechOutputSplit': Empty DataFrame
 Columns: [region, period, tech, output_comm, operator, proportion, notes, data_source, dq_cred, dq_geog, dq_struc, dq_tech, dq_time, data_id]
 Index: [],
 'LimitTechOutputSplitAnnual': Empty DataFrame
 Columns: [region, period, tech, output_comm, operator, proportion, notes, data_source, dq_cred, dq_geog, dq_struc, dq_tech, dq_time, data_id]
 Index: [],
 'LimitEmission': Empty DataFrame
 Columns: [region, period, emis_comm, operator, value, units, notes, data_source, dq_cred, dq_geog, dq_struc, dq_tech, dq_time, data_id]
 Index: [],
 'LinkedTech': Empty DataFrame
 Columns: [primary_region, primary_tech, emis_comm, driven_tech, notes, data_id]
 Index: [],
 'PlanningReserveMargin': Empty DataFrame
 Columns: [region, margin, notes, data_source, dq_cred, dq_geog, dq_struc, dq_tech, dq_time, data_id]
 Index: [],
 'RampDownHourly': Empty DataFrame
 Columns: [region, tech, rate, notes, data_source, dq_cred, dq_geog, dq_struc, dq_tech, dq_time, data_id]
 Index: [],
 'RampUpHourly': Empty DataFrame
 Columns: [region, tech, rate, notes, data_source, dq_cred, dq_geog, dq_struc, dq_tech, dq_time, data_id]
 Index: [],
 'Region': Empty DataFrame
 Columns: [region, notes]
 Index: [],
 'ReserveCapacityDerate': Empty DataFrame
 Columns: [region, period, season, tech, vintage, factor, notes, data_source, dq_cred, dq_geog, dq_struc, dq_tech, dq_time, data_id]
 Index: [],
 'TimeSegmentFraction': Empty DataFrame
 Columns: [period, season, tod, segfrac, notes]
 Index: [],
 'StorageDuration': Empty DataFrame
 Columns: [region, tech, duration, notes, data_source, dq_cred, dq_geog, dq_struc, dq_tech, dq_time, data_id]
 Index: [],
 'LifetimeSurvivalCurve': Empty DataFrame
 Columns: [region, period, tech, vintage, fraction, notes, data_source, dq_cred, dq_geog, dq_struc, dq_tech, dq_time, data_id]
 Index: [],
 'TechnologyType':   label                     description
 0     p           production technology
 1    pb  baseload production technology
 2    ps   storage production technology,
 'TimeOfDay': Empty DataFrame
 Columns: [sequence, tod]
 Index: [],
 'TimePeriod': Empty DataFrame
 Columns: [sequence, period, flag]
 Index: [],
 'TimeSeason': Empty DataFrame
 Columns: [period, sequence, season, notes]
 Index: [],
 'TimeSeasonSequential': Empty DataFrame
 Columns: [period, sequence, seas_seq, season, num_days, notes]
 Index: [],
 'TimePeriodType':   label        description
 0     e  existing vintages
 1     f             future,
 'RPSRequirement': Empty DataFrame
 Columns: [region, period, tech_group, requirement, data_source, dq_cred, dq_geog, dq_struc, dq_tech, dq_time, data_id, notes]
 Index: [],
 'TechGroupMember': Empty DataFrame
 Columns: [group_name, tech, data_id]
 Index: [],
 'Technology':          tech flag      sector category sub_category  unlim_cap  annual  \
 0       I_CON    p  industrial     None         None          1       1

In [153]:
techs_h2 = pd.read_csv('dbs/residential/fixers/industry_h2_techs.csv')['tech'].to_list()
comms_h2 = pd.read_csv('dbs/residential/fixers/industry_h2_comm.csv')['comm'].to_list()
tech_replace_h2 = pd.read_csv('dbs/residential/fixers/tech_replace.csv')
comm_replace_h2 = pd.read_csv('dbs/residential/fixers/comm_replace.csv')

transp.keys()

dict_keys(['DataSource', 'ExistingCapacity', 'DataSet', 'CapacityFactorTech', 'LimitTechInputSplitAnnual', 'LimitAnnualCapacityFactor', 'CostFixed', 'TechGroupMember', 'Technology', 'EmissionActivity', 'LifetimeTech', 'CostInvest', 'Demand', 'CapacityToActivity', 'LifetimeSurvivalCurve', 'Commodity', 'CostVariable', 'Efficiency'])

In [175]:
industry = {}

for table, df in transp.items():
    print(table)
    if 'tech' in df.columns:
        industry[table] = df[df['tech'].isin(techs_h2)].copy().reset_index(drop=True)
    else: 
        industry[table] = df.copy()
    
for table, df in transp.items():
    # 1. Create a boolean mask for the entire dataframe
    # 2. .any(axis=1) checks if 'True' appears in any column for that row
    mask = df.isin(comms_h2).any(axis=1)
    
    # Only add to the dictionary if we actually found matches
    if mask.any():
        industry[table] = df[mask].copy().reset_index(drop=True)

industry.keys()

DataSource
ExistingCapacity
DataSet
CapacityFactorTech
LimitTechInputSplitAnnual
LimitAnnualCapacityFactor
CostFixed
TechGroupMember
Technology
EmissionActivity
LifetimeTech
CostInvest
Demand
CapacityToActivity
LifetimeSurvivalCurve
Commodity
CostVariable
Efficiency

dict_keys(['DataSource', 'ExistingCapacity', 'DataSet', 'CapacityFactorTech', 'LimitTechInputSplitAnnual', 'LimitAnnualCapacityFactor', 'CostFixed', 'TechGroupMember', 'Technology', 'EmissionActivity', 'LifetimeTech', 'CostInvest', 'Demand', 'CapacityToActivity', 'LifetimeSurvivalCurve', 'Commodity', 'CostVariable', 'Efficiency'])

In [176]:
industry['Commodity']

       name flag                                description    data_id
0      T_ng    a  Natural gas for the transportation sector  FUELHR001
1  T_elc_dc    p          Electrolysis needs DC electricity   TRPHR001
2   T_h2_10    a                        Gaseous H2 @ 10 bar   TRPHR001
3  T_h2_100    a                       Gaseous H2 @ 100 bar   TRPHR001

In [208]:


tech_replace_h2 
comm_replace_h2 

for i in range(len(tech_replace_h2)):
    old_tech = tech_replace_h2.loc[i, 'original']
    new_tech = tech_replace_h2.loc[i, 'replace']
    for table, df in industry.items():
        if old_tech in df.values:
            industry[table] = df.replace(old_tech, new_tech)

for i in range(len(comm_replace_h2)):
    old_comm = comm_replace_h2.loc[i, 'original']
    new_comm = comm_replace_h2.loc[i, 'replace']
    for table, df in industry.items():
        if old_comm in df.values:
            industry[table] = df.replace(old_comm, new_comm)

industry['Commodity']
industry['Technology']['sector'] = 'industry'
industry['Technology']['data_id'] = 'INDHR001'
industry['Technology']
source = set()
for table, df in industry.items():
    try:
        print(table,df['data_source'].unique())
        source.update(df['data_source'].unique())
    except KeyError:
        pass
industry['DataSource'] = pd.read_csv('dbs/residential/fixers/DataSource_industry.csv')
industry

ExistingCapacity []
CapacityFactorTech []
LimitTechInputSplitAnnual ['T24']
LimitAnnualCapacityFactor [nan]
CostFixed ['T24' 'T23']
EmissionActivity ['F4' 'F5' 'T12']
LifetimeTech ['T03' 'T06']
CostInvest ['T24' 'T23']
Demand ['T17']
CapacityToActivity [nan]
CostVariable ['T23']
Efficiency [nan 'T12' 'T24' 'T06']

{'DataSource':   source_id                                             source  \
 0        F4  Government of Canada, Emission factors and ref...
 1        F5                                           IPCC AR6
 2       T03  DeCarolis, J. F., Jaramillo, P., Johnson, J. X...
 3       T06  IEA. (2024). Global Hydrogen Review 2024  Assu...
 4       T12  Dept. for Business, Energy & Industrial Strate...
 5       T17  Natural Resources Canada. (2023b). Transportat...
 6       T23  Plazas Nino, F., Yeganyan, R., Cannone, C., Ho...
 7       T24  DeCarolis, J. F., Jaramillo, P., Johnson, J. X...

                                                notes    data_id
 0  The appropriate emission factors for sector an...  FUELHR001
 1  Used for the GWP100 values for methane, carbon...  FUELHR001
 2                                                NaN   TRPHR001
 3                                                NaN   TRPHR001
 4                                                NaN   TRPHR001
 5                                                NaN   TRPHR001
 6                                                NaN   TRPHR001
 7                                                NaN   TRPHR001  ,
 'ExistingCapacity': Empty DataFrame
 Columns: [region, tech, vintage, capacity, units, notes, data_source, dq_cred, dq_geog, dq_struc, dq_tech, dq_time, data_id]
 Index: [],
 'DataSet':           data_id                                              label version  \
 0        TRPHR001                   Transportation - High Resolution  v1.0.0
 1      TRPHRAB001         Transportation - High Resolution - Alberta  v1.0.0
 2      TRPHRBC001  Transportation - High Resolution - British Col...  v1.0.0
 3      TRPHRMB001        Transportation - High Resolution - Manitoba  v1.0.0
 4      TRPHRNB001   Transportation - High Resolution - New Brunswick  v1.0.0
 5   TRPHRNLLAB001  Transportation - High Resolution - Newfoundlan...  v1.0.0
 6      TRPHRNS001     Transportation - High Resolution - Nova Scotia  v1.0.0
 7      TRPHRON001         Transportation - High Resolution - Ontario  v1.0.0
 8     TRPHRPEI001  Transportation - High Resolution - Prince Edwa...  v1.0.0
 9      TRPHRQC001          Transportation - High Resolution - Quebec  v1.0.0
 10     TRPHRSK001    Transportation - High Resolution - Saskatchewan  v1.0.0

                                           description  status  \
 0                    Transportation - High Resolution  active
 1          Transportation - High Resolution - Alberta  active
 2   Transportation - High Resolution - British Col...  active
 3         Transportation - High Resolution - Manitoba  active
 4    Transportation - High Resolution - New Brunswick  active
 5   Transportation - High Resolution - Newfoundlan...  active
 6      Transportation - High Resolution - Nova Scotia  active
 7          Transportation - High Resolution - Ontario  active
 8   Transportation - High Resolution - Prince Edwa...  active
 9           Transportation - High Resolution - Quebec  active
 10    Transportation - High Resolution - Saskatchewan  active

               author     date  parent_id        changelog  notes
 0   Thiago Rodrigues  10/9/25        NaN  Initial release    NaN
 1   Thiago Rodrigues  10/9/25        NaN  Initial release    NaN
 2   Thiago Rodrigues  10/9/25        NaN  Initial release    NaN
 3   Thiago Rodrigues  10/9/25        NaN  Initial release    NaN
 4   Thiago Rodrigues  10/9/25        NaN  Initial release    NaN
 5   Thiago Rodrigues  10/9/25        NaN  Initial release    NaN
 6   Thiago Rodrigues  10/9/25        NaN  Initial release    NaN
 7   Thiago Rodrigues  10/9/25        NaN  Initial release    NaN
 8   Thiago Rodrigues  10/9/25        NaN  Initial release    NaN
 9   Thiago Rodrigues  10/9/25        NaN  Initial release    NaN
 10  Thiago Rodrigues  10/9/25        NaN  Initial release    NaN  ,
 'CapacityFactorTech': Empty DataFrame
 Columns: [region, period, season, tod, tech, factor, notes, data_source, dq_cred, dq_geog, dq_struc, dq_tech, dq_time, data_id]
 Index: [],
 'LimitTechInputSplitAnnual':    region  period input_comm               tech operator  proportion  \
 0      AB    2025   I_h2_100  I_H2_COMP_100_700       ge       0.952
 1      AB    2030   I_h2_100  I_H2_COMP_100_700       ge       0.952
 2      AB    2035   I_h2_100  I_H2_COMP_100_700       ge       0.952
 3      AB    2040   I_h2_100  I_H2_COMP_100_700       ge       0.952
 4      AB    2045   I_h2_100  I_H2_COMP_100_700       ge       0.952
 ..    ...     ...        ...                ...      ...         ...
 95     SK    2025    I_h2_10   I_H2_COMP_10_100       ge       0.943
 96     SK    2030    I_h2_10   I_H2_COMP_10_100       ge       0.943
 97     SK    2035    I_h2_10   I_H2_COMP_10_100       ge       0.943
 98     SK    2040    I_h2_10   I_H2_COMP_10_100       ge       0.943
 99     SK    2045    I_h2_10   I_H2_COMP_10_100       ge       0.943

                                                 notes data_source  dq_cred  \
 0   Ratio obtained from the Open Energy Outlook 20...         T24      NaN
 1   Ratio obtained from the Open Energy Outlook 20...         T24      NaN
 2   Ratio obtained from the Open Energy Outlook 20...         T24      NaN
 3   Ratio obtained from the Open Energy Outlook 20...         T24      NaN
 4   Ratio obtained from the Open Energy Outlook 20...         T24      NaN
 ..                                                ...         ...      ...
 95  Ratio obtained from the Open Energy Outlook 20...         T24      NaN
 96  Ratio obtained from the Open Energy Outlook 20...         T24      NaN
 97  Ratio obtained from the Open Energy Outlook 20...         T24      NaN
 98  Ratio obtained from the Open Energy Outlook 20...         T24      NaN
 99  Ratio obtained from the Open Energy Outlook 20...         T24      NaN

     dq_geog  dq_struc  dq_tech  dq_time     data_id
 0       NaN       NaN      NaN      NaN  TRPHRAB001
 1       NaN       NaN      NaN      NaN  TRPHRAB001
 2       NaN       NaN      NaN      NaN  TRPHRAB001
 3       NaN       NaN      NaN      NaN  TRPHRAB001
 4       NaN       NaN      NaN      NaN  TRPHRAB001
 ..      ...       ...      ...      ...         ...
 95      NaN       NaN      NaN      NaN  TRPHRSK001
 96      NaN       NaN      NaN      NaN  TRPHRSK001
 97      NaN       NaN      NaN      NaN  TRPHRSK001
 98      NaN       NaN      NaN      NaN  TRPHRSK001
 99      NaN       NaN      NaN      NaN  TRPHRSK001

 [100 rows x 14 columns],
 'LimitAnnualCapacityFactor':     region      tech  vintage output_comm operator  factor  notes  \
 0       AB  I_H2_SMR   2025.0        T_h2       ge  0.9025    NaN
 1       AB  I_H2_SMR   2030.0        T_h2       ge  0.9025    NaN
 2       AB  I_H2_SMR   2035.0        T_h2       ge  0.9025    NaN
 3       AB  I_H2_SMR   2040.0        T_h2       ge  0.9025    NaN
 4       AB  I_H2_SMR   2045.0        T_h2       ge  0.9025    NaN
 ..     ...       ...      ...         ...      ...     ...    ...
 195     SK  I_H2_SMR   2025.0        T_h2       ge  0.9025    NaN
 196     SK  I_H2_SMR   2030.0        T_h2       ge  0.9025    NaN
 197     SK  I_H2_SMR   2035.0        T_h2       ge  0.9025    NaN
 198     SK  I_H2_SMR   2040.0        T_h2       ge  0.9025    NaN
 199     SK  I_H2_SMR   2045.0        T_h2       ge  0.9025    NaN

      data_source  dq_cred  dq_geog  dq_struc  dq_tech  dq_time     data_id
 0            NaN      NaN      NaN       NaN      NaN      NaN  TRPHRAB001
 1            NaN      NaN      NaN       NaN      NaN      NaN  TRPHRAB001
 2            NaN      NaN      NaN       NaN      NaN      NaN  TRPHRAB001
 3            NaN      NaN      NaN       NaN      NaN      NaN  TRPHRAB001
 4            NaN      NaN      NaN       NaN      NaN      NaN  TRPHRAB001
 ..           ...      ...      ...       ...      ...      ...         ...
 195          NaN      NaN      NaN       NaN      NaN      NaN  TRPHRSK001
 196          NaN      NaN      NaN       NaN      NaN      NaN  TRPHRSK001
 197          NaN      NaN      NaN       NaN      NaN      NaN  TRPHRSK001
 198          NaN      NaN      NaN       NaN      NaN      NaN  TRPHRSK001
 199          NaN      NaN      NaN       NaN      NaN      NaN  TRPHRSK001

 [200 rows x 14 columns],
 'CostFixed':     region  period              tech  vintage       cost             units  \
 0       AB    2025  I_H2_COMP_10_100     2025   6.084089  2020 CAD (M$/GW)
 1       AB    2030  I_H2_COMP_10_100     2025   6.084089  2020 CAD (M$/GW)
 2       AB    2030  I_H2_COMP_10_100     2030   6.084089  2020 CAD (M$/GW)
 3       AB    2035  I_H2_COMP_10_100     2025   6.084089  2020 CAD (M$/GW)
 4       AB    2035  I_H2_COMP_10_100     2030   6.084089  2020 CAD (M$/GW)
 ..     ...     ...               ...      ...        ...               ...
 815     SK    2045      I_H2_SMR_CCS     2025  48.142290  2020 CAD (M$/GW)
 816     SK    2045      I_H2_SMR_CCS     2030  47.210810  2020 CAD (M$/GW)
 817     SK    2045      I_H2_SMR_CCS     2035  46.297352  2020 CAD (M$/GW)
 818     SK    2045      I_H2_SMR_CCS     2040  45.401568  2020 CAD (M$/GW)
 819     SK    2045      I_H2_SMR_CCS     2045  44.523116  2020 CAD (M$/GW)

                                                  notes data_source  dq_cred  \
 0    Obtained from the Open Energy Outlook 2022; co...         T24      NaN
 1    Obtained from the Open Energy Outlook 2022; co...         T24      NaN
 2    Obtained from the Open Energy Outlook 2022; co...         T24      NaN
 3    Obtained from the Open Energy Outlook 2022; co...         T24      NaN
 4    Obtained from the Open Energy Outlook 2022; co...         T24      NaN
 ..                                                 ...         ...      ...
 815  From the Techno-Economic Energy Dataset for Hy...         T23      NaN
 816  From the Techno-Economic Energy Dataset for Hy...         T23      NaN
 817  From the Techno-Economic Energy Dataset for Hy...         T23      NaN
 818  From the Techno-Economic Energy Dataset for Hy...         T23      NaN
 819  From the Techno-Economic Energy Dataset for Hy...         T23      NaN

      dq_geog  dq_struc  dq_tech  dq_time     data_id
 0        NaN       NaN      NaN      NaN  TRPHRAB001
 1        NaN       NaN      NaN      NaN  TRPHRAB001
 2        NaN       NaN      NaN      NaN  TRPHRAB001
 3        NaN       NaN      NaN      NaN  TRPHRAB001
 4        NaN       NaN      NaN      NaN  TRPHRAB001
 ..       ...       ...      ...      ...         ...
 815      NaN       NaN      NaN      NaN  TRPHRSK001
 816      NaN       NaN      NaN      NaN  TRPHRSK001
 817      NaN       NaN      NaN      NaN  TRPHRSK001
 818      NaN       NaN      NaN      NaN  TRPHRSK001
 819      NaN       NaN      NaN      NaN  TRPHRSK001

 [820 rows x 14 columns],
 'TechGroupMember': Empty DataFrame
 Columns: [group_name, tech, data_id]
 Index: [],
 'Technology':                 tech flag    sector     category  sub_category  unlim_cap  \
 0        I_ELC_AC_DC    p  industry  Fuel supply           NaN          0
 1   I_H2_COMP_10_100    p  industry  Fuel supply           NaN          0
 2  I_H2_COMP_100_700    p  industry  Fuel supply           NaN          0
 3  I_H2_distribution    p  industry  Fuel supply           NaN          1
 4       I_H2_ELC_ALK    p  industry  Fuel supply           NaN          0
 5       I_H2_ELC_PEM    p  industry  Fuel supply           NaN          0
 6           I_H2_SMR    p  industry  Fuel supply           NaN          0
 7       I_H2_SMR_CCS    p  industry  Fuel supply           NaN          0

    annual  reserve  curtail  retire  flex  exchange  seas_stor  description  \
 0       0        0        0       0     0         0          0          NaN
 1       1        0        0       0     0         0          0          NaN
 2       1        0        0       0     0         0          0          NaN
 3       1        0        0       0     0         0          0          NaN
 4       0        0        0       0     0         0          0          NaN
 5       0        0        0       0     0         0          0          NaN
 6       1        0        0       0     0         0          0          NaN
 7       1        0        0       0     0         0          0          NaN

     data_id
 0  INDHR001
 1  INDHR001
 2  INDHR001
 3  INDHR001
 4  INDHR001
 5  INDHR001
 6  INDHR001
 7  INDHR001  ,
 'EmissionActivity':     region emis_comm input_comm          tech  vintage output_comm   activity  \
 0       AB       co2       F_ng        F_T_NG     2020        I_ng  51.876676
 1       AB       co2       F_ng        F_T_NG     2025        I_ng  51.876676
 2       AB       co2       F_ng        F_T_NG     2030        I_ng  51.876676
 3       AB       co2       F_ng        F_T_NG     2035        I_ng  51.876676
 4       AB       co2       F_ng        F_T_NG     2040        I_ng  51.876676
 ..     ...       ...        ...           ...      ...         ...        ...
 255    PEI      co2e       I_ng  I_H2_SMR_CCS     2020        T_h2 -60.332881
 256     QC       co2       I_ng  I_H2_SMR_CCS     2020        T_h2 -60.911160
 257     QC      co2e       I_ng  I_H2_SMR_CCS     2020        T_h2 -60.332881
 258     SK       co2       I_ng  I_H2_SMR_CCS     2020        T_h2 -60.911160
 259     SK      co2e       I_ng  I_H2_SMR_CCS     2020        T_h2 -60.332881

          units                                              notes data_source  \
 0    kTonne/PJ  Converted from g/m3 to kTonne/PJ, using the in...          F4
 1    kTonne/PJ  Converted from g/m3 to kTonne/PJ, using the in...          F4
 2    kTonne/PJ  Converted from g/m3 to kTonne/PJ, using the in...          F4
 3    kTonne/PJ  Converted from g/m3 to kTonne/PJ, using the in...          F4
 4    kTonne/PJ  Converted from g/m3 to kTonne/PJ, using the in...          F4
 ..         ...                                                ...         ...
 255  ktCO2e/PJ  CO2e based on 100-year horizon GWPs from the I...         T12
 256   ktCO2/PJ  CO2 captured per PJ of natural gas utilized fo...         T12
 257  ktCO2e/PJ  CO2e based on 100-year horizon GWPs from the I...         T12
 258   ktCO2/PJ  CO2 captured per PJ of natural gas utilized fo...         T12
 259  ktCO2e/PJ  CO2e based on 100-year horizon GWPs from the I...         T12

      dq_cred  dq_geog  dq_struc  dq_tech  dq_time      data_id
 0        1.0      2.0       2.0      2.0      2.0  FUELHRAB001
 1        1.0      2.0       2.0      2.0      2.0  FUELHRAB001
 2        1.0      2.0       2.0      2.0      2.0  FUELHRAB001
 3        1.0      2.0       2.0      2.0      2.0  FUELHRAB001
 4        1.0      2.0       2.0      2.0      2.0  FUELHRAB001
 ..       ...      ...       ...      ...      ...          ...
 255      NaN      NaN       NaN      NaN      NaN  TRPHRPEI001
 256      NaN      NaN       NaN      NaN      NaN   TRPHRQC001
 257      NaN      NaN       NaN      NaN      NaN   TRPHRQC001
 258      NaN      NaN       NaN      NaN      NaN   TRPHRSK001
 259      NaN      NaN       NaN      NaN      NaN   TRPHRSK001

 [260 rows x 16 columns],
 'LifetimeTech':    region               tech  lifetime  \
 0      AB        I_ELC_AC_DC      25.0
 1      AB   I_H2_COMP_10_100      15.0
 2      AB  I_H2_COMP_100_700      15.0
 3      AB       I_H2_ELC_ALK      20.0
 4      AB       I_H2_ELC_PEM      20.0
 ..    ...                ...       ...
 65     SK  I_H2_COMP_100_700      15.0
 66     SK       I_H2_ELC_ALK      20.0
 67     SK       I_H2_ELC_PEM      20.0
 68     SK           I_H2_SMR      25.0
 69     SK       I_H2_SMR_CCS      25.0

                                                 notes data_source  dq_cred  \
 0   Lifetime obtained from the Open Energy Outlook...         T03      NaN
 1   Lifetime obtained from the Open Energy Outlook...         T03      NaN
 2   Lifetime obtained from the Open Energy Outlook...         T03      NaN
 3   Derived with the same approach as the Open Ene...         T03      NaN
 4   Derived with the same approach as the Open Ene...         T03      NaN
 ..                                                ...         ...      ...
 65  Lifetime obtained from the Open Energy Outlook...         T03      NaN
 66  Derived with the same approach as the Open Ene...         T03      NaN
 67  Derived with the same approach as the Open Ene...         T03      NaN
 68  From the IEA Global Hydrogen Review 2024 assum...         T06      NaN
 69  From the IEA Global Hydrogen Review 2024 assum...         T06      NaN

     dq_geog  dq_struc  dq_tech  dq_time     data_id
 0       NaN       NaN      NaN      NaN  TRPHRAB001
 1       NaN       NaN      NaN      NaN  TRPHRAB001
 2       NaN       NaN      NaN      NaN  TRPHRAB001
 3       NaN       NaN      NaN      NaN  TRPHRAB001
 4       NaN       NaN      NaN      NaN  TRPHRAB001
 ..      ...       ...      ...      ...         ...
 65      NaN       NaN      NaN      NaN  TRPHRSK001
 66      NaN       NaN      NaN      NaN  TRPHRSK001
 67      NaN       NaN      NaN      NaN  TRPHRSK001
 68      NaN       NaN      NaN      NaN  TRPHRSK001
 69      NaN       NaN      NaN      NaN  TRPHRSK001

 [70 rows x 11 columns],
 'CostInvest':     region          tech  vintage         cost             units  \
 0       AB   I_ELC_AC_DC     2025   352.663211  2020 CAD (M$/GW)
 1       AB   I_ELC_AC_DC     2030   352.663211  2020 CAD (M$/GW)
 2       AB   I_ELC_AC_DC     2035   352.663211  2020 CAD (M$/GW)
 3       AB   I_ELC_AC_DC     2040   352.663211  2020 CAD (M$/GW)
 4       AB   I_ELC_AC_DC     2045   352.663211  2020 CAD (M$/GW)
 ..     ...           ...      ...          ...               ...
 345     SK  I_H2_SMR_CCS     2025  1208.035609  2020 CAD (M$/GW)
 346     SK  I_H2_SMR_CCS     2030  1184.661942  2020 CAD (M$/GW)
 347     SK  I_H2_SMR_CCS     2035  1161.740520  2020 CAD (M$/GW)
 348     SK  I_H2_SMR_CCS     2040  1139.262592  2020 CAD (M$/GW)
 349     SK  I_H2_SMR_CCS     2045  1117.219579  2020 CAD (M$/GW)

                                                  notes data_source  dq_cred  \
 0           Obtained from the Open Energy Outlook 2022         T24      NaN
 1           Obtained from the Open Energy Outlook 2022         T24      NaN
 2           Obtained from the Open Energy Outlook 2022         T24      NaN
 3           Obtained from the Open Energy Outlook 2022         T24      NaN
 4           Obtained from the Open Energy Outlook 2022         T24      NaN
 ..                                                 ...         ...      ...
 345  From the Techno-Economic Energy Dataset for Hy...         T23      NaN
 346  From the Techno-Economic Energy Dataset for Hy...         T23      NaN
 347  From the Techno-Economic Energy Dataset for Hy...         T23      NaN
 348  From the Techno-Economic Energy Dataset for Hy...         T23      NaN
 349  From the Techno-Economic Energy Dataset for Hy...         T23      NaN

      dq_geog  dq_struc  dq_tech  dq_time     data_id
 0        NaN       NaN      NaN      NaN  TRPHRAB001
 1        NaN       NaN      NaN      NaN  TRPHRAB001
 2        NaN       NaN      NaN      NaN  TRPHRAB001
 3        NaN       NaN      NaN      NaN  TRPHRAB001
 4        NaN       NaN      NaN      NaN  TRPHRAB001
 ..       ...       ...      ...      ...         ...
 345      NaN       NaN      NaN      NaN  TRPHRSK001
 346      NaN       NaN      NaN      NaN  TRPHRSK001
 347      NaN       NaN      NaN      NaN  TRPHRSK001
 348      NaN       NaN      NaN      NaN  TRPHRSK001
 349      NaN       NaN      NaN      NaN  TRPHRSK001

 [350 rows x 13 columns],
 'Demand':     region  period      commodity     demand units  \
 0       AB    2025     T_D_pj_off  16.124138    PJ
 1       AB    2030     T_D_pj_off  17.368281    PJ
 2       AB    2035     T_D_pj_off  18.619543    PJ
 3       AB    2040     T_D_pj_off  19.852416    PJ
 4       AB    2045     T_D_pj_off  21.257884    PJ
 ..     ...     ...            ...        ...   ...

In [199]:
industry.keys()

dict_keys(['DataSource', 'ExistingCapacity', 'DataSet', 'CapacityFactorTech', 'LimitTechInputSplitAnnual', 'LimitAnnualCapacityFactor', 'CostFixed', 'TechGroupMember', 'Technology', 'EmissionActivity', 'LifetimeTech', 'CostInvest', 'Demand', 'CapacityToActivity', 'LifetimeSurvivalCurve', 'Commodity', 'CostVariable', 'Efficiency'])

In [212]:
db_industry = 'dbs/residential/industry.sqlite'
# os.remove(db_industry) if os.path.exists(db_industry) else None
# mgmt.convert_sql_to_sqlite(data_schema, db_industry)
mgmt.update_sqlite(db_industry, industry)

Inserting into DataSource with columns: source_id,source,notes,data_id
Inserting into ExistingCapacity with columns: region,tech,vintage,capacity,units,notes,data_source,dq_cred,dq_geog,dq_struc,dq_tech,dq_time,data_id
Inserting into DataSet with columns: data_id,label,version,description,status,author,date,parent_id,changelog,notes
Inserting into CapacityFactorTech with columns: region,period,season,tod,tech,factor,notes,data_source,dq_cred,dq_geog,dq_struc,dq_tech,dq_time,data_id
Inserting into LimitTechInputSplitAnnual with columns: region,period,input_comm,tech,operator,proportion,notes,data_source,dq_cred,dq_geog,dq_struc,dq_tech,dq_time,data_id
Inserting into LimitAnnualCapacityFactor with columns: region,tech,vintage,output_comm,operator,factor,notes,data_source,dq_cred,dq_geog,dq_struc,dq_tech,dq_time,data_id
Inserting into CostFixed with columns: region,period,tech,vintage,cost,units,notes,data_source,dq_cred,dq_geog,dq_struc,dq_tech,dq_time,data_id
Inserting into TechGroupMember with columns: group_name,tech,data_id
Inserting into Technology with columns: tech,flag,sector,category,sub_category,unlim_cap,annual,reserve,curtail,retire,flex,exchange,seas_stor,description,data_id
Inserting into EmissionActivity with columns: region,emis_comm,input_comm,tech,vintage,output_comm,activity,units,notes,data_source,dq_cred,dq_geog,dq_struc,dq_tech,dq_time,data_id
Inserting into LifetimeTech with columns: region,tech,lifetime,notes,data_source,dq_cred,dq_geog,dq_struc,dq_tech,dq_time,data_id
Inserting into CostInvest with columns: region,tech,vintage,cost,units,notes,data_source,dq_cred,dq_geog,dq_struc,dq_tech,dq_time,data_id
Inserting into Demand with columns: region,period,commodity,demand,units,notes,data_source,dq_cred,dq_geog,dq_struc,dq_tech,dq_time,data_id
Inserting into CapacityToActivity with columns: region,tech,c2a,notes,data_id,data_source,dq_cred,dq_geog,dq_struc,dq_tech,dq_time
Inserting into LifetimeSurvivalCurve with columns: region,tech,vintage,period,fraction,notes,data_id
Inserting into Commodity with columns: name,flag,description,data_id
Inserting into CostVariable with columns: region,period,tech,vintage,cost,units,notes,data_source,dq_cred,dq_geog,dq_struc,dq_tech,dq_time,data_id
Inserting into Efficiency with columns: region,input_comm,tech,vintage,output_comm,efficiency,notes,data_source,dq_cred,dq_geog,dq_struc,dq_tech,dq_time,data_id

In [ ]:
db_fuel = 'dbs/canoe_fuel.sqlite'
os.remove(db_fuel) if os.path.exists(db_fuel) else None
mgmt.convert_sql_to_sqlite(data_schema, db_fuel)
data_fuel = mgmt.sqlite_to_dfs(db_fuel)

In [189]:
# _db = mgmt.sqlite_to_dfs('dbs/canoe_all.sqlite')
mgmt.sqlite_to_excel('dbs/canoe_all.sqlite', 'canoe_all.xlsx', sheets='all')

Exporting table: CapacityCredit
Exporting table: CapacityFactorProcess
Exporting table: CapacityFactorTech
Exporting table: CapacityToActivity
Exporting table: Commodity
Exporting table: CommodityType
Exporting table: ConstructionInput
Exporting table: CostEmission
Exporting table: CostFixed
Exporting table: CostInvest
Exporting table: CostVariable
Exporting table: DataQualityCredibility
Exporting table: DataQualityGeography
Exporting table: DataQualityStructure
Exporting table: DataQualityTechnology
Exporting table: DataQualityTime
Exporting table: DataSet
Exporting table: DataSource
Exporting table: Demand
Exporting table: DemandSpecificDistribution
Exporting table: Efficiency
Exporting table: EfficiencyVariable
Exporting table: EmissionActivity
Exporting table: EmissionEmbodied
Exporting table: EmissionEndOfLife
Exporting table: EndOfLifeOutput
Exporting table: ExistingCapacity
Exporting table: LifetimeProcess
Exporting table: LifetimeSurvivalCurve
Exporting table: LifetimeTech
Exporting table: LimitActivity
Exporting table: LimitActivityShare
Exporting table: LimitAnnualCapacityFactor
Exporting table: LimitCapacity
Exporting table: LimitCapacityShare
Exporting table: LimitDegrowthCapacity
Exporting table: LimitDegrowthNewCapacity
Exporting table: LimitDegrowthNewCapacityDelta
Exporting table: LimitEmission
Exporting table: LimitGrowthCapacity
Exporting table: LimitGrowthNewCapacity
Exporting table: LimitGrowthNewCapacityDelta
Exporting table: LimitNewCapacity
Exporting table: LimitNewCapacityShare
Exporting table: LimitResource
Exporting table: LimitSeasonalCapacityFactor
Exporting table: LimitStorageLevelFraction
Exporting table: LimitTechInputSplit
Exporting table: LimitTechInputSplitAnnual
Exporting table: LimitTechOutputSplit
Exporting table: LimitTechOutputSplitAnnual
Exporting table: LinkedTech
Exporting table: LoanLifetimeProcess
Exporting table: LoanRate
Exporting table: MetaData
Exporting table: MetaDataReal
Exporting table: Operator
Exporting table: OutputBuiltCapacity
Exporting table: OutputCost
Exporting table: OutputCurtailment
Exporting table: OutputDualVariable
Exporting table: OutputEmission
Exporting table: OutputFlowIn
Exporting table: OutputFlowOut
Exporting table: OutputNetCapacity
Exporting table: OutputObjective
Exporting table: OutputRetiredCapacity
Exporting table: OutputStorageLevel
Exporting table: PlanningReserveMargin
Exporting table: RPSRequirement
Exporting table: RampDownHourly
Exporting table: RampUpHourly
Exporting table: Region
Exporting table: ReserveCapacityDerate
Exporting table: SeasonLabel
Exporting table: SectorLabel
Exporting table: StorageDuration
Exporting table: TechGroup
Exporting table: TechGroupMember
Exporting table: Technology
Exporting table: TechnologyType
Exporting table: TimeOfDay
Exporting table: TimePeriod
Exporting table: TimePeriodType
Exporting table: TimeSeason
Exporting table: TimeSeasonSequential
Exporting table: TimeSegmentFraction

In [58]:
_db['Technology'].to_csv('fuel/inputs/Technology.csv', index=False)

In [59]:
_db

{'MetaData':            element  value                         notes
 0         DB_MAJOR      3       DB major version number
 1         DB_MINOR      1       DB minor version number
 2  days_per_period    363  count of days in each period,
 'MetaDataReal':                 element  value                          notes
 0  global_discount_rate   0.03  Canadian social discount rate
 1     default_loan_rate   0.03                   Matching GDR,
 'SeasonLabel':   season notes
 0   D119  None
 1   D133  None
 2   D136  None
 3   D183  None
 4   D273  None
 5   D320  None
 6   D321  None
 7   D326  None,
 'SectorLabel': Empty DataFrame
 Columns: [sector, notes]
 Index: [],
 'CapacityCredit':      region  period            tech  vintage    credit  \
 0        AB    2025     E_BIO_M-EXS     1995  0.888424
 1        AB    2030     E_BIO_M-EXS     1995  0.888424
 2        AB    2035     E_BIO_M-EXS     1995  0.888424
 3        AB    2025     E_BIO_M-EXS     2000  0.888424
 4        AB    2030     E_BIO_M-EXS     2000  0.888424
 ...     ...     ...             ...      ...       ...
 5946     SK    2050  E_SOL_PV-NEW-1     2050  0.177557
 5947     SK    2050  E_SOL_PV-NEW-2     2050  0.159924
 5948     SK    2050  E_SOL_PV-NEW-3     2050  0.164918
 5949     SK    2050  E_SOL_PV-NEW-4     2050  0.159385
 5950     SK    2050  E_SOL_PV-NEW-5     2050  0.164532

                                                   notes data_source  dq_cred  \
 0     Forecasted capability at firm summer peak divi...         E16      1.0
 1     Forecasted capability at firm summer peak divi...         E16      1.0
 2     Forecasted capability at firm summer peak divi...         E16      1.0
 3     Forecasted capability at firm summer peak divi...         E16      1.0
 4     Forecasted capability at firm summer peak divi...         E16      1.0
 ...                                                 ...         ...      ...
 5946  NREL ReEDS method (NREL, 2017). Marginal net l...        None      NaN
 5947  NREL ReEDS method (NREL, 2017). Marginal net l...        None      NaN
 5948  NREL ReEDS method (NREL, 2017). Marginal net l...        None      NaN
 5949  NREL ReEDS method (NREL, 2017). Marginal net l...        None      NaN
 5950  NREL ReEDS method (NREL, 2017). Marginal net l...        None      NaN

       dq_geog  dq_struc  dq_tech  dq_time     data_id
 0         1.0       2.0      2.0      3.0  ELCHRAB001
 1         1.0       2.0      2.0      3.0  ELCHRAB001
 2         1.0       2.0      2.0      3.0  ELCHRAB001
 3         1.0       2.0      2.0      3.0  ELCHRAB001
 4         1.0       2.0      2.0      3.0  ELCHRAB001
 ...       ...       ...      ...      ...         ...
 5946      NaN       NaN      NaN      NaN  ELCHRSK001
 5947      NaN       NaN      NaN      NaN  ELCHRSK001
 5948      NaN       NaN      NaN      NaN  ELCHRSK001
 5949      NaN       NaN      NaN      NaN  ELCHRSK001
 5950      NaN       NaN      NaN      NaN  ELCHRSK001

 [5951 rows x 13 columns],
 'CapacityFactorProcess':        region  period season  tod            tech  vintage    factor  \
 0          AB    2025   D119  H01  E_WND_ON-NEW-1     2025  0.779168
 1          AB    2025   D119  H02  E_WND_ON-NEW-1     2025  0.740651
 2          AB    2025   D119  H03  E_WND_ON-NEW-1     2025  0.627950
 3          AB    2025   D119  H04  E_WND_ON-NEW-1     2025  0.476261
 4          AB    2025   D119  H05  E_WND_ON-NEW-1     2025  0.409357
 ...       ...     ...    ...  ...             ...      ...       ...
 725755     SK    2050   D326  H20  E_SOL_PV-NEW-5     2050  0.000000
 725756     SK    2050   D326  H21  E_SOL_PV-NEW-5     2050  0.000000
 725757     SK    2050   D326  H22  E_SOL_PV-NEW-5     2050  0.000000
 725758     SK    2050   D326  H23  E_SOL_PV-NEW-5     2050  0.000000
 725759     SK    2050   D326  H24  E_SOL_PV-NEW-5     2050  0.000000

                                                     notes data_source dq_cred  \
 0       Wind characterisation work done by Sutubra. Gr...        None    None
 1                                                    None        None    None
 2                                                    None        None    None
 3                                                    None        None    None
 4                                                    None        None    None
 ...                                                   ...         ...     ...
 725755                                               None        None    None
 725756                                               None        None    None
 725757                                               None        None    None
 725758                                               None        None    None
 725759                                               None        None    None

        dq_geog dq_struc dq_tech dq_time     data_id
 0         None     None    None    None  ELCHRAB001
 1         None     None    None    None  ELCHRAB001
 2         None     None    None    None  ELCHRAB001
 3         None     None    None    None  ELCHRAB001
 4         None     None    None    None  ELCHRAB001
 ...        ...      ...     ...     ...         ...
 725755    None     None    None    None  ELCHRSK001
 725756    None     None    None    None  ELCHRSK001
 725757    None     None    None    None  ELCHRSK001
 725758    None     None    None    None  ELCHRSK001
 725759    None     None    None    None  ELCHRSK001

 [725760 rows x 15 columns],
 'CapacityFactorTech':       region  period season  tod            tech    factor  \
 0         AB    2025   D119  H01    E_SOL_PV-EXS  0.000000
 1         AB    2025   D119  H02    E_SOL_PV-EXS  0.000000
 2         AB    2025   D119  H03    E_SOL_PV-EXS  0.000000
 3         AB    2025   D119  H04    E_SOL_PV-EXS  0.000000
 4         AB    2025   D119  H05    E_SOL_PV-EXS  0.000000
 ...      ...     ...    ...  ...             ...       ...
 56059     SK    2050   D326  H20  T_LDV_BEV_CHRG  0.801328
 56060     SK    2050   D326  H21  T_LDV_BEV_CHRG  0.710235
 56061     SK    2050   D326  H22  T_LDV_BEV_CHRG  0.547546
 56062     SK    2050   D326  H23  T_LDV_BEV_CHRG  0.489667
 56063     SK    2050   D326  H24  T_LDV_BEV_CHRG  0.470510

                                                    notes data_source  dq_cred  \
 0      Hourly capacity factors from Renewables Ninja ...         E15      3.0
 1                                                   None        None      NaN
 2                                                   None        None      NaN
 3                                                   None        None      NaN
 4                                                   None        None      NaN
 ...                                                  ...         ...      ...
 56059                                               None        None      NaN
 56060                                               None        None      NaN
 56061                                               None        None      NaN
 56062                                               None        None      NaN
 56063                                               None        None      NaN

        dq_geog  dq_struc  dq_tech  dq_time     data_id
 0          1.0       2.0      2.0      3.0  ELCHRAB001
 1          NaN       NaN      NaN      NaN  ELCHRAB001
 2          NaN       NaN      NaN      NaN  ELCHRAB001
 3          NaN       NaN      NaN      NaN  ELCHRAB001
 4          NaN       NaN      NaN      NaN  ELCHRAB001
 ...        ...       ...      ...      ...         ...
 56059      NaN       NaN      NaN      NaN  TRPHRSK001
 56060      NaN       NaN      NaN      NaN  TRPHRSK001
 56061      NaN       NaN      NaN      NaN  TRPHRSK001
 56062      NaN       NaN      NaN      NaN  TRPHRSK001
 56063      NaN       NaN      NaN      NaN  TRPHRSK001

 [56064 rows x 14 columns],
 'CapacityToActivity':      region                tech    c2a  \
 0        AB        C_SPH_NG-EXS  1.000
 1        AB       C_SPH_ELC-EXS  1.000
 2        AB   C_SPHC_HP_AIR-NEW  1.000
 3        AB   C_SPHC_HP_GEO-NEW  1.000
 4        AB   C_SPH_ELC_BLR-NEW  1.000
 ...     ...                 ...    ...
 1877     SK  T_MDV_T_DSL_PHEV_N  0.975
 1878     SK      T_MDV_T_FCEV_N  0.975
 1879     SK     T_MDV_T_FCHEV_N  0.975
 1880     SK      T_MDV_T_GSL_EX  0.650
 1881     SK       T_MDV_T_GSL_N  0.650

                                                   notes data_source dq_cred  \
 0        Capacity is in PJ/y and activity is in PJ so 1        None    None
 1        Capacity is in PJ/y and activity is in PJ so 1        None    None
 2        Capacity is in PJ/y and activity is in PJ so 1        None    None
 3        Capacity is in PJ/y and activity is in PJ so 1        None    None
 4        Capacity is in PJ/y and activity is in PJ so 1        None    None
 ...                                                 ...         ...     ...
 1877  [btkm/k units] An estimate of how much activit...        None    None
 1878  [btkm/k units] An estimate of how much activit...        None    None
 1879  [btkm/k units] An estimate of how much activit...        None    None
 1880  [btkm/k units] An estimate of how much activit...        None    None
 1881  [btkm/k units] An estimate of how much activit...        None    None

      dq_geog dq_struc dq_tech dq_time     data_id
 0       None     None    None    None  COMHRAB001
 1       None     None    None    None  COMHRAB001
 2       None     None    None    None  COMHRAB001
 3       None     None    None    None  COMHRAB001
 4       None     None    None    None  COMHRAB001
 ...      ...      ...     ...     ...         ...
 1877    None     None    None    None  TRPHRSK001
 1878    None     None    None    None  TRPHRSK001
 1879    None     None    None    None  TRPHRSK001
 1880    None     None    None    None  TRPHRSK001
 1881    None     None    None    None  TRPHRSK001

 [1882 rows x 11 columns],
 'Commodity':             name flag                                        description  \
 0          A_elc    p   Represents Electricity in the agriculture sector
 1           A_ng    a   Represents Natural Gas in the agriculture sector
 2          A_dsl    a        Represents Diesel in the agriculture sector
 3          A_gsl    a      Represents Gasoline in the agriculture sector
 4       A_d_agri    d                  Demand for the Agriculture sector
 ..           ...  ...                                                ...
 132     T_h2_hdv    a  Gaseous H2 @ 700 bar for use in heavy-duty veh...
 133     T_h2_ldv    a  Gaseous H2 @ 700 bar for use in light-duty veh...
 134     T_h2_mdv    a  Gaseous H2 @ 700 bar for use in medium-duty ve...
 135  T_jtf_spk50    a           Conventional jet fuel with 50% HEFA SPK
 136   T_jtf_spkX    a  Conv. jet fuel, after potential blending with ...

        data_id
 0    AGRIHR001
 1    AGRIHR001
 2    AGRIHR001
 3    AGRIHR001
 4    AGRIHR001
 ..         ...
 132   TRPHR001
 133   TRPHR001
 134   TRPHR001
 135   TRPHR001
 136   TRPHR001

 [137 rows x 4 columns],
 'CommodityType':   label               description
 0     s          source commodity
 1     a          annual commodity
 2     p        physical commodity
 3     d          demand commodity
 4     e       emissions commodity
 5     w           waste commodity
 6    wa    waste annual commodity
 7    wp  waste physical commodity,
 'ConstructionInput': Empty DataFrame
 Columns: [region, input_comm, tech, vintage, value, units, notes, data_source, dq_cred, dq_geog, dq_struc, dq_tech, dq_time, data_id]
 Index: [],
 'CostEmission': Empty DataFrame
 Columns: [region, period, emis_comm, cost, units, notes, data_source, dq_cred, dq_geog, dq_struc, dq_tech, dq_time, data_id]
 Index: [],
 'CostFixed':       region  period          tech  vintage      cost  units  \
 0         AB    2025  C_SPH_NG-EXS     2005  0.177534  M$/PJ
 1         AB    2025  C_SPH_NG-EXS     2010  0.177534  M$/PJ
 2         AB    2030  C_SPH_NG-EXS     2010  0.177534  M$/PJ
 3         AB    2025  C_SPH_NG-EXS     2015  0.177534  M$/PJ
 4         AB    2030  C_SPH_NG-EXS     2015  0.177534  M$/PJ
 ...      ...     ...           ...      ...       ...    ...
 12811     NB    2045    T_MDV_CHRG     2040  1.643260   None
 12812     NB    2050    T_MDV_CHRG     2040  1.643260   None
 12813     NB    2045    T_MDV_CHRG     2045  1.643260   None
 12814     NB    2050    T_MDV_CHRG     2045  1.643260   None
 12815     NB    2050    T_MDV_CHRG     2050  1.643260   None

                                                    notes data_source  dq_cred  \
 0      Average maintenance cost of installed stock in...         C01      1.0
 1      Average maintenance cost of installed stock in...         C01      1.0
 2      Average maintenance cost of installed stock in...         C01      1.0
 3      Average maintenance cost of installed stock in...         C01      1.0
 4      Average maintenance cost of installed stock in...         C01      1.0
 ...                                                  ...         ...      ...
 12811                                               None        None      NaN
 12812                                               None        None      NaN
 12813                                               None        None      NaN
 12814                                               None        None      NaN
 12815                                               None        None      NaN

        dq_geog  dq_struc  dq_tech  dq_time     data_id
 0          2.0       1.0      2.0      2.0  COMHRAB001
 1          2.0       1.0      2.0      2.0  COMHRAB001
 2          2.0       1.0      2.0      2.0  COMHRAB001
 3          2.0       1.0      2.0      2.0  COMHRAB001
 4          2.0       1.0      2.0      2.0  COMHRAB001
 ...        ...       ...      ...      ...         ...
 12811      NaN       NaN      NaN      NaN        None
 12812      NaN       NaN      NaN      NaN        None
 12813      NaN       NaN      NaN      NaN        None
 12814      NaN       NaN      NaN      NaN        None
 12815      NaN       NaN      NaN      NaN        None

 [12816 rows x 14 columns],
 'CostInvest':      region               tech  vintage        cost    units  \
 0        AB  C_SPHC_HP_AIR-NEW     2025   18.789329  M$/PJ/y
 1        AB  C_SPHC_HP_AIR-NEW     2030   18.789329  M$/PJ/y
 2        AB  C_SPHC_HP_AIR-NEW     2035   18.789329  M$/PJ/y
 3        AB  C_SPHC_HP_AIR-NEW     2040   18.789329  M$/PJ/y
 4        AB  C_SPHC_HP_AIR-NEW     2045   18.789329  M$/PJ/y
 ...     ...                ...      ...         ...      ...
 8559     NB         T_HDV_CHRG     2030  164.325982     None
 8560     NB         T_HDV_CHRG     2035  164.325982     None
 8561     NB         T_HDV_CHRG     2040  164.325982     None
 8562     NB         T_HDV_CHRG     2045  164.325982     None
 8563     NB         T_HDV_CHRG     2050  164.325982     None

                                                   notes data_source  dq_cred  \
 0     Capcst from AEO CDM ktekx technology menu for ...         C01      1.0
 1     Capcst from AEO CDM ktekx technology menu for ...         C01      1.0
 2     Capcst from AEO CDM ktekx technology menu for ...         C01      1.0
 3     Capcst from AEO CDM ktekx technology menu for ...         C01      1.0
 4     Capcst from AEO CDM ktekx technology menu for ...         C01      1.0
 ...                                                 ...         ...      ...
 8559  Weighted average of 50 kW, 150 kW, and 350 kW ...        None      NaN
 8560  Weighted average of 50 kW, 150 kW, and 350 kW ...        None      NaN
 8561  Weighted average of 50 kW, 150 kW, and 350 kW ...        None      NaN
 8562  Weighted average of 50 kW, 150 kW, and 350 kW ...        None      NaN
 8563  Weighted average of 50 kW, 150 kW, and 350 kW ...        None      NaN

       dq_geog  dq_struc  dq_tech  dq_time     data_id
 0         2.0       1.0      2.0      2.0  COMHRAB001
 1         2.0       1.0      2.0      2.0  COMHRAB001
 2         2.0       1.0      2.0      2.0  COMHRAB001
 3         2.0       1.0      2.0      2.0  COMHRAB001
 4         2.0       1.0      2.0      2.0  COMHRAB001
 ...       ...       ...      ...      ...         ...
 8559      NaN       NaN      NaN      NaN        None
 8560      NaN       NaN      NaN      NaN        None
 8561      NaN       NaN      NaN      NaN        None
 8562      NaN       NaN      NaN      NaN        None
 8563      NaN       NaN      NaN      NaN        None

 [8564 rows x 13 columns],
 'CostVariable':       region  period           tech  vintage        cost               units  \
 0         AB    2025      F_E_BIO_M     2025    6.042383          2020 M$/PJ
 1         AB    2025       F_E_COAL     2025    8.635175          2020 M$/PJ
 2         AB    2025      F_E_U_ENR     2025    1.208557          2020 M$/PJ
 3         AB    2025        F_R_LPG     2025   20.044112          2020 M$/PJ
 4         AB    2025         F_T_H2     2025   68.523438          2020 M$/PJ
 ...      ...     ...            ...      ...         ...                 ...
 24215     SK    2045  T_MDV_T_GSL_N     2040  219.074159  2020 CAD (M$/btkm)
 24216     SK    2050  T_MDV_T_GSL_N     2040  261.608854  2020 CAD (M$/btkm)
 24217     SK    2045  T_MDV_T_GSL_N     2045  137.380516  2020 CAD (M$/btkm)
 24218     SK    2050  T_MDV_T_GSL_N     2045  219.074159  2020 CAD (M$/btkm)
 24219     SK    2050  T_MDV_T_GSL_N     2050  137.380516  2020 CAD (M$/btkm)

                                                    notes data_source  dq_cred  \
 0                                        solid bioenergy          F1      2.0
 1                                                   coal          F1      2.0
 2                                       enriched uranium          F1      2.0
 3      liquefied petroleum gas (LPG) (primarily propane)          F1      2.0
 4                                               hydrogen          F1      2.0
 ...                                                  ...         ...      ...
 24215  Gasoline fuel type costs were derived using AF...         T21      NaN
 24216  Gasoline fuel type costs were derived using AF...         T21      NaN
 24217  Gasoline fuel type costs were derived using AF...         T21      NaN
 24218  Gasoline fuel type costs were derived using AF...         T21      NaN
 24219  Gasoline fuel type costs were derived using AF...         T21      NaN

        dq_geog  dq_struc  dq_tech  dq_time      data_id
 0          3.0       2.0      1.0      1.0  FUELHRAB001
 1          3.0       2.0      1.0      1.0  FUELHRAB001
 2          3.0       2.0      1.0      1.0  FUELHRAB001
 3          3.0       2.0      1.0      1.0  FUELHRAB001
 4          3.0       2.0      1.0      1.0  FUELHRAB001
 ...        ...       ...      ...      ...          ...
 24215      NaN       NaN      NaN      NaN   TRPHRSK001
 24216      NaN       NaN      NaN      NaN   TRPHRSK001
 24217      NaN       NaN      NaN      NaN   TRPHRSK001
 24218      NaN       NaN      NaN      NaN   TRPHRSK001
 24219      NaN       NaN      NaN      NaN   TRPHRSK001

 [24220 rows x 14 columns],
 'Demand':      region  period      commodity     demand units  \
 0        AB    2025       A_d_agri  62.100000    PJ
 1        AB    2030       A_d_agri  68.617256    PJ
 2        AB    2035       A_d_agri  73.496756    PJ
 3        AB    2040       A_d_agri  76.372708    PJ
 4        AB    2045       A_d_agri  79.615349    PJ
 ...     ...     ...            ...        ...   ...
 2341     SK    2030  T_D_tkm_mdv_t   4.343773  btkm
 2342     SK    2035  T_D_tkm_mdv_t   4.678940  btkm
 2343     SK    2040  T_D_tkm_mdv_t   5.016025  btkm
 2344     SK    2045  T_D_tkm_mdv_t   5.348155  btkm
 2345     SK    2050  T_D_tkm_mdv_t   5.726782  btkm

                                                   notes data_source  dq_cred  \

In [72]:
_fuel = mgmt.sqlite_to_dfs('dbs/residential/fuel.sqlite')
_elec = mgmt.sqlite_to_dfs('dbs/residential/electricity.sqlite')

In [69]:
_fuel['Technology']['sector'] = 'fuel'
_fuel['Technology']

,tech,flag,sector,category,sub_category,unlim_cap,annual,reserve,curtail,retire,flex,exchange,seas_stor,description,data_id
0,F_E_BIO_G,p,fuel,None,None,1,1,0,0,0,0,0,0,Gaseous bioenergy distribution from fuel secto...,FUELHR002
1,F_E_BIO_M,p,fuel,None,None,1,1,0,0,0,0,0,0,Solid bioenergy distribution from fuel sector ...,FUELHR002
2,F_E_NG,p,fuel,None,None,1,1,0,0,0,0,0,0,Natural gas distribution from fuel sector to e...,FUELHR002
3,F_E_COAL,p,fuel,None,None,1,1,0,0,0,0,0,0,Coal distribution from fuel sector to electric...,FUELHR002
4,F_E_OIL,p,fuel,None,None,1,1,0,0,0,0,0,0,Oil distribution from fuel sector to electric ...,FUELHR002
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74,F_IMP_RDSL,p,fuel,None,None,1,1,0,0,0,0,0,0,Renewable diesel import into fuel sector,FUELHR002
75,F_IMP_SPK,p,fuel,None,None,1,1,0,0,0,0,0,0,Synthetic jet fuel import into fuel sector,FUELHR002
76,F_IMP_U_ENR,p,fuel,None,None,1,1,0,0,0,0,0,0,Enriched uranium import into fuel sector,FUELHR002
77,F_IMP_U_NAT,p,fuel,None,None,1,1,0,0,0,0,0,0,Natural uranium import into fuel sector,FUELHR002
78,F_IMP_WOOD,p,fuel,None,None,1,1,0,0,0,0,0,0,Wood import into fuel sector,FUELHR002

In [73]:
for tech in fuel['Technology']['tech'].to_list():
    if tech not in _fuel['Technology']['tech'].to_list():
        print('not in fuel: ', tech)
    if tech not in _elec['Technology']['tech'].to_list():
        print('not in elec: ', tech)

not in elec:  E_T_ELC
not in elec:  F_T_H2
not in elec:  F_T_NG
not in elec:  F_T_HFO
not in elec:  F_T_GSL
not in elec:  F_T_ETH
not in elec:  F_T_DSL
not in elec:  F_T_RDSL
not in elec:  F_T_CNG
not in elec:  F_T_JTF
not in elec:  F_T_SPK
not in elec:  F_T_MDO
not in elec:  F_T_LNG
not in fuel:  T_ELC_AC_DC
not in elec:  T_ELC_AC_DC
not in fuel:  T_H2_COMP_10_100
not in elec:  T_H2_COMP_10_100
not in fuel:  T_H2_COMP_100_700
not in elec:  T_H2_COMP_100_700
not in fuel:  T_H2_distribution
not in elec:  T_H2_distribution
not in fuel:  T_I_H2_ELC_ALK
not in elec:  T_I_H2_ELC_ALK
not in fuel:  T_I_H2_ELC_PEM
not in elec:  T_I_H2_ELC_PEM
not in fuel:  T_I_H2_SMR
not in elec:  T_I_H2_SMR
not in fuel:  T_I_H2_SMR_CCS
not in elec:  T_I_H2_SMR_CCS

In [75]:
fuel['Technology'].to_csv('dbs/replaced_techs.csv', index=False)

In [258]:
techs_trans = new_transp['Technology']['tech'].to_list()
techs_trans

['T_BLND_DSL_ELC_HDV',
 'T_BLND_DSL_ELC_MDV',
 'T_BLND_ETH_GSL',
 'T_BLND_GSL_ELC_PHEV35',
 'T_BLND_GSL_ELC_PHEV50',
 'T_BLND_JTF',
 'T_BLND_RDSL_DSL',
 'T_BLND_SPK',
 'T_H2_HDV_REFUEL',
 'T_H2_LDV_REFUEL',
 'T_H2_MDV_REFUEL',
 'T_HDV_AJF_JFL',
 'T_HDV_AJF_SPK',
 'T_HDV_AJP_JFL',
 'T_HDV_AJP_SPK',
 'T_HDV_BIC_BEV',
 'T_HDV_BIC_DSL',
 'T_HDV_BIC_DSL_HEV',
 'T_HDV_BIC_FCEV',
 'T_HDV_BIC_GSL',
 'T_HDV_BS_BEV',
 'T_HDV_BS_CNG',
 'T_HDV_BS_DSL',
 'T_HDV_BS_DSL_HEV',
 'T_HDV_BS_DSL_PHEV',
 'T_HDV_BS_FCEV',
 'T_HDV_BS_FCHEV',
 'T_HDV_BS_GSL',
 'T_HDV_BT_BEV',
 'T_HDV_BT_CNG',
 'T_HDV_BT_DSL',
 'T_HDV_BT_DSL_HEV',
 'T_HDV_BT_DSL_PHEV',
 'T_HDV_BT_FCEV',
 'T_HDV_BT_FCHEV',
 'T_HDV_BT_GSL',
 'T_HDV_CHRG',
 'T_HDV_RF_DSL',
 'T_HDV_RF_H2',
 'T_HDV_RF_LNG',
 'T_HDV_RICP_DSL',
 'T_HDV_RICP_H2',
 'T_HDV_T_BEV',
 'T_HDV_T_DSL',
 'T_HDV_T_DSL_HEV',
 'T_HDV_T_DSL_PHEV',
 'T_HDV_T_FCEV',
 'T_HDV_T_FCHEV',
 'T_HDV_WTF_HFO',
 'T_HDV_WTF_LNG',
 'T_HDV_WTF_MDO',
 'T_LDV_BEV_CHRG',
 'T_LDV_C_BEV150',
 'T_LDV_C_BEV200',
 'T_LDV_C_BEV300',
 'T_LDV_C_BEV400',
 'T_LDV_C_CNG',
 'T_LDV_C_DSL',
 'T_LDV_C_FCEV400',
 'T_LDV_C_GSL',
 'T_LDV_C_GSL_HEV',
 'T_LDV_C_GSL_PHEV35',
 'T_LDV_C_GSL_PHEV50',
 'T_LDV_LTF_BEV150',
 'T_LDV_LTF_BEV200',
 'T_LDV_LTF_BEV300',
 'T_LDV_LTF_BEV400',
 'T_LDV_LTF_CNG',
 'T_LDV_LTF_DSL',
 'T_LDV_LTF_FCEV400',
 'T_LDV_LTF_GSL',
 'T_LDV_LTF_GSL_HEV',
 'T_LDV_LTF_GSL_PHEV35',
 'T_LDV_LTF_GSL_PHEV50',
 'T_LDV_LTP_BEV150',
 'T_LDV_LTP_BEV200',
 'T_LDV_LTP_BEV300',
 'T_LDV_LTP_BEV400',
 'T_LDV_LTP_CNG',
 'T_LDV_LTP_DSL',
 'T_LDV_LTP_FCEV400',
 'T_LDV_LTP_GSL',
 'T_LDV_LTP_GSL_HEV',
 'T_LDV_LTP_GSL_PHEV35',
 'T_LDV_LTP_GSL_PHEV50',
 'T_LDV_M_BEV',
 'T_LDV_M_GSL',
 'T_LDV_PHEV_CHRG',
 'T_MDV_CHRG',
 'T_MDV_T_BEV',
 'T_MDV_T_DSL',
 'T_MDV_T_DSL_HEV',
 'T_MDV_T_DSL_PHEV',
 'T_MDV_T_FCEV',
 'T_MDV_T_FCHEV',
 'T_MDV_T_GSL',
 'T_OFF']

,region,tech,lifetime,notes,data_source,dq_cred,dq_geog,dq_struc,dq_tech,dq_time,data_id
0,AB,T_H2_HDV_REFUEL,10.0,Obtained from Hydrogen Delivery Scenario Analy...,T13,NaN,NaN,NaN,NaN,NaN,TRPHRAB002
1,AB,T_H2_LDV_REFUEL,10.0,Obtained from Hydrogen Delivery Scenario Analy...,T13,NaN,NaN,NaN,NaN,NaN,TRPHRAB002
2,AB,T_H2_MDV_REFUEL,10.0,Obtained from Hydrogen Delivery Scenario Analy...,T13,NaN,NaN,NaN,NaN,NaN,TRPHRAB002
3,AB,T_HDV_AJF_JFL,24.0,Median lifetime based on Exhibits 1-3 illustra...,T02,NaN,NaN,NaN,NaN,NaN,TRPHRAB002
4,AB,T_HDV_AJF_JF,24.0,Median lifetime based on Exhibits 1-3 illustra...,T02,NaN,NaN,NaN,NaN,NaN,TRPHRAB002
...,...,...,...,...,...,...,...,...,...,...,...
1041,SK,T_MDV_T_BEV,42.0,(y) age when vehicles have 0% survival rate,NaN,NaN,NaN,NaN,NaN,NaN,TRPHRSK002
1042,SK,T_MDV_T_DSL_HEV,42.0,(y) age when vehicles have 0% survival rate,NaN,NaN,NaN,NaN,NaN,NaN,TRPHRSK002
1043,SK,T_MDV_T_DSL_PHEV,42.0,(y) age when vehicles have 0% survival rate,NaN,NaN,NaN,NaN,NaN,NaN,TRPHRSK002
1044,SK,T_MDV_T_FCEV,42.0,(y) age when vehicles have 0% survival rate,NaN,NaN,NaN,NaN,NaN,NaN,TRPHRSK002
1045,SK,T_MDV_T_FCHEV,42.0,(y) age when vehicles have 0% survival rate,NaN,NaN,NaN,NaN,NaN,NaN,TRPHRSK002